### ISSUE TITLE
Teacher review week 4

### ISSUE THREAD

**Issue by KrispyKremeSavage** [Navodit1603/m222-KrustyKrabs#19]

**Comment by jm1021** [comment]
AK is working ratings.  Navodit working on database.  Kevin on UI development.  Eshaan working on CSS.  1.0

**Comment by jm1021** [comment]
I created a pull request to keep organization according to my request: https://github.com/Navodit1603/m222-KrustyKrabs/pull/22

**Comment by jm1021** [comment]
General comments.   There is nothing in review column.   Only two individuals listed things on Scrum board, but neither has tangible assets or links.   Video is showing some good team progress and ideation.   It is very difficult to find things through Issues to back up progress.  No self grade?

**Comment by jm1021** [comment]
AK, 
Did the video "alone".   Which represents team points are 1.5 of 2 with video.  I would have like to see participation with others and better technical descriptions to complement runtime demo.
Individually, I see tickets with Check Box completion in In progress.  Link in README has no tangibles 1/2
Journal I see test score and some comments in Eshan shared journal.  No notes from TPT or Tech Talks 4.5/5
7/10 + .25 for doing video

In your case, a great place to link TPT presentation would be your journal.

**Comment by jm1021** [comment]
Eshan,
1.5 of 2 as AK submitted video on behalf of team and it shows progress.
0/2 on individual, not sure what you are working on and no evidence in README or elsewhere
3/5 on journal and test prep.  no notes for weeek.
4.5/10

**Comment by jm1021** [comment]
Kevin,
1.5/2 for team, see comments above
1.5/2 for individual,  I see that you moved ticket into completed and have README link.  Improvement would be to have tangibles direction on the Issue.  I believe there is evidence in journal, just move to tickets.  Also, ensure your scrum master moves it to review for my visibility.
4.75/5 on journal and test prep.  Improvement would be to take notes on TPT or TT.

**Comment by jm1021** [comment]
Navodit
1.5/2 on team
1.0/2.0 for individual.  Did not see attempt to time box on readme.  Did not see checkboxes on in progress.  I see the tickets but they are not in fashion for me to review.
4.75/5 on journal and test prep.  You and Kevin seem to be placing PBL in journal.  Please keep journal for things like tech talks, TPT, and learning from Unit.  Move PBL stuff to README or Issues as evidence.

In your case, a great place to link TPT presentation would be your journal.

**Comment by jm1021** [comment]
Please link this review into your Week 4 Time box of README.
